/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContractPaymentTermEditor: typeof import('./src/components/ContractPaymentTermEditor.vue')['default']
    ContractPaymentTermSummary: typeof import('./src/components/ContractPaymentTermSummary.vue')['default']
    CustomerSelect: typeof import('./src/components/CustomerSelect.vue')['default']
    ExpenseItemEditor: typeof import('./src/components/ExpenseItemEditor.vue')['default']
    ExpenseSummary: typeof import('./src/components/ExpenseSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
